name: Train Model

on:
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.6"
      
      # Log into Azure differently depending on the base branch name
      - name: Azure Login - Development
        if: ${{ github.base_ref=='develop' }}
        shell: bash
        run: echo "Development"
      - name: Azure Login - Main
        if: ${{ github.base_ref=='main' }}
        shell: bash
        run: echo "Development"