name: Train Model

on:
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.6"
      
      # Log into Azure differently depending on the base branch name
      - name: Azure Login - Development
        if: ${{ github.base_ref=='develop' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AML_CREDS_DEV }}
      
      - name: Azure Login - Main
        if: ${{ github.base_ref=='main' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AML_CREDS_PROD }}

      - name: List Environments
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az ml workspace list
      
      - name: Configure Workspace
        uses: azure/CLI@v1
        with:
          inlineScript: |
            make config

      - name: Run Training
        uses: azure/CLI@v1
        with:
          inlineScript: |
            make train